import type {
  Employee,
  EmployeeDailyStatus,
  ShiftInfo,
  Station,
  StationAssignment,
  WorkArea,
} from "./types";

export const mockWorkDate = "2026-04-16";

export const mockShifts: ShiftInfo[] = [
  { code: "shift_1", label: "1st Shift", time_range: "05:00-07:30" },
  { code: "shift_2", label: "2nd Shift", time_range: "07:45-09:30" },
  { code: "shift_3", label: "3rd Shift", time_range: "10:00-12:00" },
];

export const mockWorkAreas: WorkArea[] = [
  {
    id: "wa_loading",
    name: "Loading Dock",
    color_hex: "#0f172a",
    display_order: 1,
  },
  {
    id: "wa_small",
    name: "Small Pro",
    color_hex: "#0f172a",
    display_order: 2,
  },
  {
    id: "wa_processing",
    name: "Processing Floor",
    color_hex: "#0f172a",
    display_order: 3,
  },
  {
    id: "wa_meat",
    name: "Meat Cutting",
    color_hex: "#0f172a",
    display_order: 4,
    mode_views: [
      { mode_code: "hog_break", label: "Hog Break", time_range: "05:00 - 09:00" },
      { mode_code: "after_hog_break", label: "After Hog Break", time_range: "09:30 - 10:00" },
    ],
  },
  {
    id: "wa_packaging",
    name: "Packaging",
    color_hex: "#0f172a",
    display_order: 5,
    mode_views: [
      { mode_code: "hog_break", label: "Hog Break", time_range: "05:00 - 09:00" },
      { mode_code: "after_hog_break", label: "After Hog Break", time_range: "09:30 - 10:00" },
    ],
  },
];

export const mockStations: Station[] = [
  // Loading Dock
  { id: "st_loading_supervisor", work_area_id: "wa_loading", name: "Supervisor", required_headcount: 1, display_order: 0, protected: true },
  { id: "st_loading_helper_1", work_area_id: "wa_loading", name: "Helper #1", required_headcount: 1, display_order: 2, group: "Operations" },
  { id: "st_loading_hogselector", work_area_id: "wa_loading", name: "Hog Selector", required_headcount: 1, display_order: 3, group: "Operations" },
  { id: "st_loading_cooler", work_area_id: "wa_loading", name: "Cooler", required_headcount: 1, display_order: 4, group: "Support" },
  { id: "st_loading_maps_helper", work_area_id: "wa_loading", name: "Maps / Helper", required_headcount: 1, display_order: 5, group: "Support" },
  { id: "st_loading_helper_2", work_area_id: "wa_loading", name: "Helper #2", required_headcount: 1, display_order: 6, group: "Helpers" },
  { id: "st_loading_helper_3", work_area_id: "wa_loading", name: "Helper #3", required_headcount: 1, display_order: 7, group: "Helpers" },
  { id: "st_loading_helper_4", work_area_id: "wa_loading", name: "Helper #4", required_headcount: 1, display_order: 8, group: "Helpers" },
  { id: "st_loading_helper_5", work_area_id: "wa_loading", name: "Helper #5", required_headcount: 1, display_order: 9, group: "Helpers" },
  { id: "st_loading_helper_6", work_area_id: "wa_loading", name: "Helper #6", required_headcount: 1, display_order: 10, group: "Helpers" },
  // Small Pro
  { id: "st_small_supervisor", work_area_id: "wa_small", name: "Supervisor", required_headcount: 1, display_order: 0, protected: true },
  { id: "st_small_slab_off", work_area_id: "wa_small", name: "Slab Off", required_headcount: 1, display_order: 1, group: "Slabs" },
  { id: "st_small_slab_on", work_area_id: "wa_small", name: "Slab On", required_headcount: 1, display_order: 2, group: "Slabs" },
  { id: "st_small_slab_garlic", work_area_id: "wa_small", name: "Slab Garlic", required_headcount: 1, display_order: 3, group: "Slabs" },
  { id: "st_small_slab_jalapeno", work_area_id: "wa_small", name: "Slab Jalapeno", required_headcount: 1, display_order: 4, group: "Slabs" },
  { id: "st_small_slab_maple", work_area_id: "wa_small", name: "Slab Maple", required_headcount: 1, display_order: 5, group: "Slabs" },
  { id: "st_small_slab_nna", work_area_id: "wa_small", name: "Slab NNA", required_headcount: 1, display_order: 6, group: "Slabs" },
  { id: "st_small_slab_sugar_free", work_area_id: "wa_small", name: "Slab Sugar Free", required_headcount: 1, display_order: 7, group: "Slabs" },
  { id: "st_small_euro", work_area_id: "wa_small", name: "Euro", required_headcount: 1, display_order: 8, group: "Specialty Cuts" },
  { id: "st_small_sandwich", work_area_id: "wa_small", name: "Sandwich", required_headcount: 1, display_order: 9, group: "Specialty Cuts" },
  { id: "st_small_jowl", work_area_id: "wa_small", name: "Jowl", required_headcount: 1, display_order: 10, group: "Specialty Cuts" },
  { id: "st_small_back_rib", work_area_id: "wa_small", name: "Back Rib", required_headcount: 1, display_order: 11, group: "Specialty Cuts" },
  { id: "st_small_spare_rib", work_area_id: "wa_small", name: "Spare Rib", required_headcount: 1, display_order: 12, group: "Specialty Cuts" },
  { id: "st_small_banquet", work_area_id: "wa_small", name: "Banquet", required_headcount: 1, display_order: 13, group: "Other" },
  { id: "st_small_kaiser", work_area_id: "wa_small", name: "Kaiser", required_headcount: 1, display_order: 14, group: "Other" },
  { id: "st_small_custom", work_area_id: "wa_small", name: "Custom", required_headcount: 1, display_order: 15, group: "Other" },
  // Processing Floor
  { id: "st_proc_supervisor", work_area_id: "wa_processing", name: "Supervisor", required_headcount: 1, display_order: 0, protected: true },
  { id: "st_proc_barn_setup", work_area_id: "wa_processing", name: "Barn Set Up (45 min-1 hr)", required_headcount: 1, display_order: 1, group: "Set Up" },
  { id: "st_proc_blood_pit", work_area_id: "wa_processing", name: "Set Up Blood pit (30 min)", required_headcount: 1, display_order: 2, group: "Set Up" },
  { id: "st_proc_clean_side", work_area_id: "wa_processing", name: "Set Up Clean side (30 min)", required_headcount: 1, display_order: 3, group: "Set Up" },
  { id: "st_proc_blood_setup", work_area_id: "wa_processing", name: "Blood Set-up (approx 15 min)", required_headcount: 1, display_order: 4, group: "Set Up" },
  { id: "st_proc_suckling_tank", work_area_id: "wa_processing", name: "Set up suckling tank (approx 10 min)", required_headcount: 1, display_order: 5, group: "Set Up" },
  { id: "st_proc_rollers_gams", work_area_id: "wa_processing", name: "Unload rollers and gams (2 staff 15 min)", required_headcount: 2, display_order: 6, group: "Operations" },
  { id: "st_proc_bone_heads", work_area_id: "wa_processing", name: "Bone Heads", required_headcount: 1, display_order: 7, group: "Operations" },
  // Meat Cutting - Main Room (Hog Break)
  { id: "st_meat_supervisor", work_area_id: "wa_meat", name: "Supervisor", required_headcount: 1, display_order: 0, mode_code: "hog_break", protected: true },
  { id: "st_meat_saw", work_area_id: "wa_meat", name: "Saw", required_headcount: 1, display_order: 1, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_neck_bones", work_area_id: "wa_meat", name: "Neck Bones", required_headcount: 1, display_order: 2, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_proof", work_area_id: "wa_meat", name: "Proof", required_headcount: 1, display_order: 3, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_skinner", work_area_id: "wa_meat", name: "Skinner", required_headcount: 1, display_order: 4, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_whiz_knife", work_area_id: "wa_meat", name: "Whiz Knife Legs", required_headcount: 1, display_order: 5, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_picnic_1", work_area_id: "wa_meat", name: "Picnic", required_headcount: 1, display_order: 6, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_picnic_2", work_area_id: "wa_meat", name: "Picnic", required_headcount: 1, display_order: 7, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_rib_1", work_area_id: "wa_meat", name: "Rib / Grade / Trim", required_headcount: 1, display_order: 8, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_rib_2", work_area_id: "wa_meat", name: "Rib / Grade / Trim", required_headcount: 1, display_order: 9, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_loin_trim", work_area_id: "wa_meat", name: "Loin Puller: Trim", required_headcount: 1, display_order: 10, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_loin_butt", work_area_id: "wa_meat", name: "Loin/Butt Puller: Operate", required_headcount: 1, display_order: 11, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_butt_trim", work_area_id: "wa_meat", name: "Butt Puller: Trim", required_headcount: 1, display_order: 12, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_small_saw", work_area_id: "wa_meat", name: "Small Saw", required_headcount: 1, display_order: 13, mode_code: "hog_break", group: "Main Room" },
  { id: "st_meat_float", work_area_id: "wa_meat", name: "Main Room Float", required_headcount: 1, display_order: 14, mode_code: "hog_break", group: "Main Room" },
  // Meat Cutting - Bellies (Hog Break)
  { id: "st_meat_bellies_1", work_area_id: "wa_meat", name: "S'less Trim / Bellies", required_headcount: 1, display_order: 15, mode_code: "hog_break", group: "Bellies" },
  { id: "st_meat_bellies_2", work_area_id: "wa_meat", name: "S'less Trim / Bellies", required_headcount: 1, display_order: 16, mode_code: "hog_break", group: "Bellies" },
  { id: "st_meat_bellies_3", work_area_id: "wa_meat", name: "S'less Trim / Bellies", required_headcount: 1, display_order: 17, mode_code: "hog_break", group: "Bellies" },
  { id: "st_meat_bellies_4", work_area_id: "wa_meat", name: "S'less Trim / Bellies", required_headcount: 1, display_order: 18, mode_code: "hog_break", group: "Bellies" },
  // Meat Cutting - Cutting Room (Hog Break)
  { id: "st_meat_cr_proof", work_area_id: "wa_meat", name: "Cutting Room - Proof", required_headcount: 1, display_order: 19, mode_code: "hog_break", group: "Cutting Room" },
  { id: "st_meat_cr_1", work_area_id: "wa_meat", name: "Cutting Room", required_headcount: 1, display_order: 20, mode_code: "hog_break", group: "Cutting Room" },
  { id: "st_meat_cr_2", work_area_id: "wa_meat", name: "Cutting Room", required_headcount: 1, display_order: 21, mode_code: "hog_break", group: "Cutting Room" },
  // Packaging (Hog Break)
  { id: "st_supervisor", work_area_id: "wa_packaging", name: "Supervisor", required_headcount: 1, display_order: 0, mode_code: "hog_break", protected: true },
  { id: "st_lead", work_area_id: "wa_packaging", name: "Main Room - Lead Hand", required_headcount: 1, display_order: 2, mode_code: "hog_break", group: "Main Room" },
  { id: "st_feed", work_area_id: "wa_packaging", name: "Feed Line", required_headcount: 1, display_order: 3, mode_code: "hog_break", group: "Main Room" },
  { id: "st_end", work_area_id: "wa_packaging", name: "End of the Line Bag/ Box product", required_headcount: 2, display_order: 4, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_box_trim", work_area_id: "wa_packaging", name: "Box Trim/ Bones (80%, 50%)", required_headcount: 1, display_order: 5, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_dump_barrels", work_area_id: "wa_packaging", name: "Dump Barrels/ Clean up", required_headcount: 1, display_order: 6, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_bellie", work_area_id: "wa_packaging", name: "Bellie packaging", required_headcount: 1, display_order: 7, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_floater", work_area_id: "wa_packaging", name: "Floater", required_headcount: 1, display_order: 8, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_overstock", work_area_id: "wa_packaging", name: "Overstock Order", required_headcount: 1, display_order: 9, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_offal", work_area_id: "wa_packaging", name: "Offal", required_headcount: 1, display_order: 10, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_sungiven", work_area_id: "wa_packaging", name: "Sungiven", required_headcount: 1, display_order: 11, mode_code: "hog_break", group: "Main Room" },
  { id: "st_pack_downstairs_lead", work_area_id: "wa_packaging", name: "DownStairs / Vac Pac - Lead Hand", required_headcount: 1, display_order: 12, mode_code: "hog_break", group: "Downstairs" },
  { id: "st_pack_vac_pac_bag", work_area_id: "wa_packaging", name: "Vac Pac / Bag", required_headcount: 1, display_order: 13, mode_code: "hog_break", group: "Downstairs" },
  { id: "st_pack_vac_pac_box", work_area_id: "wa_packaging", name: "Vac pac & box", required_headcount: 1, display_order: 14, mode_code: "hog_break", group: "Downstairs" },
  { id: "st_pack_forklift", work_area_id: "wa_packaging", name: "Operate Forklift", required_headcount: 1, display_order: 15, mode_code: "hog_break", group: "Downstairs" },
  // Meat Cutting - Main Room (After Hog Break)
  { id: "st_ahb_meat_supervisor", work_area_id: "wa_meat", name: "Supervisor", required_headcount: 1, display_order: 0, mode_code: "after_hog_break", protected: true },
  { id: "st_ahb_meat_saw", work_area_id: "wa_meat", name: "Saw", required_headcount: 1, display_order: 1, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_proof", work_area_id: "wa_meat", name: "Proof", required_headcount: 1, display_order: 2, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_skinner", work_area_id: "wa_meat", name: "Skinner", required_headcount: 1, display_order: 3, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_picnic", work_area_id: "wa_meat", name: "Picnic", required_headcount: 1, display_order: 4, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_rib", work_area_id: "wa_meat", name: "Rib / Grade / Trim", required_headcount: 1, display_order: 5, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_loin_trim", work_area_id: "wa_meat", name: "Loin Puller: Trim", required_headcount: 1, display_order: 6, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_loin_butt", work_area_id: "wa_meat", name: "Loin/Butt Puller: Operate", required_headcount: 1, display_order: 7, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_butt_trim", work_area_id: "wa_meat", name: "Butt Puller: Trim", required_headcount: 1, display_order: 8, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_small_saw", work_area_id: "wa_meat", name: "Small Saw", required_headcount: 1, display_order: 9, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_meat_cleanup", work_area_id: "wa_meat", name: "Main Room Cleanup", required_headcount: 1, display_order: 10, mode_code: "after_hog_break", group: "Main Room" },
  // Meat Cutting - Bellies (After Hog Break)
  { id: "st_ahb_meat_bellies_1", work_area_id: "wa_meat", name: "S'less Trim / Bellies", required_headcount: 1, display_order: 11, mode_code: "after_hog_break", group: "Bellies" },
  { id: "st_ahb_meat_bellies_2", work_area_id: "wa_meat", name: "S'less Trim / Bellies", required_headcount: 1, display_order: 12, mode_code: "after_hog_break", group: "Bellies" },
  { id: "st_ahb_meat_bellies_3", work_area_id: "wa_meat", name: "S'less Trim / Bellies", required_headcount: 1, display_order: 13, mode_code: "after_hog_break", group: "Bellies" },
  // Meat Cutting - Cutting Room (After Hog Break)
  { id: "st_ahb_meat_cr_1", work_area_id: "wa_meat", name: "Cutting Room", required_headcount: 1, display_order: 14, mode_code: "after_hog_break", group: "Cutting Room" },
  { id: "st_ahb_meat_cr_2", work_area_id: "wa_meat", name: "Cutting Room", required_headcount: 1, display_order: 15, mode_code: "after_hog_break", group: "Cutting Room" },
  { id: "st_ahb_meat_wash", work_area_id: "wa_meat", name: "Wash Down", required_headcount: 2, display_order: 16, mode_code: "after_hog_break", group: "Cutting Room" },
  // Packaging (After Hog Break)
  { id: "st_ahb_supervisor", work_area_id: "wa_packaging", name: "Supervisor", required_headcount: 1, display_order: 0, mode_code: "after_hog_break", protected: true },
  { id: "st_ahb_lead", work_area_id: "wa_packaging", name: "Main Room - Lead Hand", required_headcount: 1, display_order: 2, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_feed", work_area_id: "wa_packaging", name: "Feed Line", required_headcount: 1, display_order: 3, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_end", work_area_id: "wa_packaging", name: "End of Line Bag/ Box product", required_headcount: 2, display_order: 4, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_pack_bellie", work_area_id: "wa_packaging", name: "Bellie packaging", required_headcount: 1, display_order: 5, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_pack_floater", work_area_id: "wa_packaging", name: "Floater", required_headcount: 1, display_order: 6, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_pack_offal", work_area_id: "wa_packaging", name: "Offal", required_headcount: 1, display_order: 7, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_pack_vac_pac", work_area_id: "wa_packaging", name: "Vac Pac / Bag", required_headcount: 1, display_order: 8, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_pack_vac_box", work_area_id: "wa_packaging", name: "Vac pac & box", required_headcount: 1, display_order: 9, mode_code: "after_hog_break", group: "Main Room" },
  { id: "st_ahb_pack_downstairs", work_area_id: "wa_packaging", name: "DownStairs - Lead Hand", required_headcount: 1, display_order: 10, mode_code: "after_hog_break", group: "Downstairs" },
  { id: "st_ahb_pack_sungiven", work_area_id: "wa_packaging", name: "Sungiven", required_headcount: 1, display_order: 11, mode_code: "after_hog_break", group: "Downstairs" },
  { id: "st_ahb_pack_cleanup", work_area_id: "wa_packaging", name: "Line Cleanup", required_headcount: 2, display_order: 12, mode_code: "after_hog_break", group: "Downstairs" },
  { id: "st_ahb_pack_forklift", work_area_id: "wa_packaging", name: "Operate Forklift", required_headcount: 1, display_order: 13, mode_code: "after_hog_break", group: "Downstairs" },
];

export const mockEmployees: Employee[] = [
  { id: "emp_1",   employee_code: "E001", full_name: "Margareta",        departments: ["Packaging"],                          active: true, gender: "F", level: 3 },
  { id: "emp_2",   employee_code: "E002", full_name: "Oana",             departments: ["Packaging"],                          active: true, gender: "F", level: 2 },
  { id: "emp_3",   employee_code: "E003", full_name: "Josh Miller",      departments: ["Meat Cutting", "Small Pro"],           active: true, gender: "M", level: 3 },
  { id: "emp_4",   employee_code: "E004", full_name: "Harpreet",         departments: ["Meat Cutting"],                       active: true, gender: "M", level: 2 },
  { id: "emp_5",   employee_code: "E005", full_name: "Daniel",           departments: ["Loading Dock"],                       active: true, gender: "M", level: 3 },
  { id: "emp_6",   employee_code: "E006", full_name: "Mina",             departments: ["Small Pro", "Packaging"],             active: true, gender: "F", level: 2 },
  { id: "emp_7",   employee_code: "E007", full_name: "Alex",             departments: ["Meat Cutting"],                       active: true, gender: "M", level: 3 },
  { id: "emp_8",   employee_code: "E008", full_name: "Ryan Cooper",      departments: ["Loading Dock", "Processing Floor"],   active: true, gender: "M", level: 2 },
  { id: "emp_9",   employee_code: "E009", full_name: "Alberto",          departments: ["Packaging"],                          active: true, gender: "M", level: 3 },
  { id: "emp_10",  employee_code: "E010", full_name: "Anthony",          departments: ["Packaging"],                          active: true, gender: "M", level: 2 },
  { id: "emp_11",  employee_code: "E011", full_name: "Sandra Kowalski",  departments: ["Processing Floor", "Loading Dock"],   active: true, gender: "F", level: 3 },
  { id: "emp_12",  employee_code: "E012", full_name: "James Nguyen",     departments: ["Meat Cutting"],                       active: true, gender: "M", level: 2 },
  { id: "emp_13",  employee_code: "E013", full_name: "Priya Sharma",     departments: ["Packaging"],                          active: true, gender: "F", level: 2 },
  { id: "emp_14",  employee_code: "E014", full_name: "Carlos Reyes",     departments: ["Loading Dock", "Small Pro"],          active: true, gender: "M", level: 2 },
  { id: "emp_15",  employee_code: "E015", full_name: "Elena Vasquez",    departments: ["Small Pro"],                          active: true, gender: "F", level: 3 },
  { id: "emp_16",  employee_code: "E016", full_name: "Tommy Larsen",     departments: ["Meat Cutting", "Packaging"],          active: true, gender: "M", level: 2 },
  { id: "emp_17",  employee_code: "E017", full_name: "Fatima Al-Hassan", departments: ["Processing Floor"],                   active: true, gender: "F", level: 2 },
  { id: "emp_18",  employee_code: "E018", full_name: "David Park",       departments: ["Packaging"],                          active: true, gender: "M", level: 1 },
  { id: "emp_19",  employee_code: "E019", full_name: "Nina Petrov",      departments: ["Small Pro", "Meat Cutting"],          active: true, gender: "F", level: 2 },
  { id: "emp_20",  employee_code: "E020", full_name: "Marcus Williams",  departments: ["Loading Dock"],                       active: true, gender: "M", level: 3 },
  // Loading Dock
  { id: "emp_21",  employee_code: "E021", full_name: "Kevin O'Brien",    departments: ["Loading Dock"],                       active: true, gender: "M", level: 2 },
  { id: "emp_22",  employee_code: "E022", full_name: "Dmitri Volkov",    departments: ["Loading Dock", "Processing Floor"],   active: true, gender: "M", level: 1 },
  { id: "emp_23",  employee_code: "E023", full_name: "Aisha Patel",      departments: ["Loading Dock"],                       active: true, gender: "F", level: 2 },
  { id: "emp_24",  employee_code: "E024", full_name: "Luca Ferretti",    departments: ["Loading Dock"],                       active: true, gender: "M", level: 1 },
  { id: "emp_25",  employee_code: "E025", full_name: "Yemi Adeyemi",     departments: ["Loading Dock"],                       active: true, gender: "M", level: 2 },
  // Small Pro
  { id: "emp_26",  employee_code: "E026", full_name: "Grace Kim",        departments: ["Small Pro", "Loading Dock"],          active: true, gender: "F", level: 2 },
  { id: "emp_27",  employee_code: "E027", full_name: "Marco Silva",      departments: ["Small Pro"],                          active: true, gender: "M", level: 1 },
  { id: "emp_28",  employee_code: "E028", full_name: "Olga Marchetti",   departments: ["Small Pro", "Meat Cutting"],          active: true, gender: "F", level: 3 },
  { id: "emp_29",  employee_code: "E029", full_name: "Ben Okafor",       departments: ["Small Pro"],                          active: true, gender: "M", level: 1 },
  { id: "emp_30",  employee_code: "E030", full_name: "Chloe Dupont",     departments: ["Small Pro"],                          active: true, gender: "F", level: 2 },
  // Processing Floor
  { id: "emp_31",  employee_code: "E031", full_name: "Victor Hernandez", departments: ["Processing Floor", "Packaging"],      active: true, gender: "M", level: 3 },
  { id: "emp_32",  employee_code: "E032", full_name: "Amara Diallo",     departments: ["Processing Floor"],                   active: true, gender: "F", level: 1 },
  { id: "emp_33",  employee_code: "E033", full_name: "Patrick Walsh",    departments: ["Processing Floor", "Small Pro"],      active: true, gender: "M", level: 2 },
  { id: "emp_34",  employee_code: "E034", full_name: "Yuki Tanaka",      departments: ["Processing Floor"],                   active: true, gender: "M", level: 2 },
  { id: "emp_35",  employee_code: "E035", full_name: "Rosa Gutierrez",   departments: ["Processing Floor"],                   active: true, gender: "F", level: 1 },
  { id: "emp_36",  employee_code: "E036", full_name: "Ivan Sokolov",     departments: ["Processing Floor"],                   active: true, gender: "M", level: 2 },
  { id: "emp_37",  employee_code: "E037", full_name: "Nadia Osei",       departments: ["Processing Floor"],                   active: true, gender: "F", level: 3 },
  // Meat Cutting
  { id: "emp_38",  employee_code: "E038", full_name: "Sean Murphy",      departments: ["Meat Cutting", "Processing Floor"],   active: true, gender: "M", level: 3 },
  { id: "emp_39",  employee_code: "E039", full_name: "Mei Lin",          departments: ["Meat Cutting"],                       active: true, gender: "F", level: 2 },
  { id: "emp_40",  employee_code: "E040", full_name: "Andrei Popescu",   departments: ["Meat Cutting", "Loading Dock"],       active: true, gender: "M", level: 3 },
  { id: "emp_41",  employee_code: "E041", full_name: "Fatou Camara",     departments: ["Meat Cutting"],                       active: true, gender: "F", level: 1 },
  { id: "emp_42",  employee_code: "E042", full_name: "Diego Morales",    departments: ["Meat Cutting"],                       active: true, gender: "M", level: 2 },
  { id: "emp_43",  employee_code: "E043", full_name: "Hana Novak",       departments: ["Meat Cutting", "Small Pro"],          active: true, gender: "F", level: 2 },
  { id: "emp_44",  employee_code: "E044", full_name: "Tunde Bakare",     departments: ["Meat Cutting"],                       active: true, gender: "M", level: 1 },
  { id: "emp_45",  employee_code: "E045", full_name: "Leila Nasser",     departments: ["Meat Cutting"],                       active: true, gender: "F", level: 2 },
  // Packaging
  { id: "emp_46",  employee_code: "E046", full_name: "Pierre Dubois",    departments: ["Packaging", "Meat Cutting"],          active: true, gender: "M", level: 2 },
  { id: "emp_47",  employee_code: "E047", full_name: "Lakshmi Iyer",     departments: ["Packaging"],                          active: true, gender: "F", level: 1 },
  { id: "emp_48",  employee_code: "E048", full_name: "Connor O'Sullivan", departments: ["Packaging", "Processing Floor"],     active: true, gender: "M", level: 2 },
  { id: "emp_49",  employee_code: "E049", full_name: "Zara Ahmed",       departments: ["Packaging"],                          active: true, gender: "F", level: 1 },
  { id: "emp_50",  employee_code: "E050", full_name: "Mikael Lindqvist", departments: ["Packaging"],                          active: true, gender: "M", level: 3 },
  // Loading Dock
  { id: "emp_51",  employee_code: "E051", full_name: "Maria Chen",       departments: ["Loading Dock"],                       active: true, gender: "F", level: 1 },
  { id: "emp_52",  employee_code: "E052", full_name: "Andre Laurent",    departments: ["Loading Dock", "Small Pro"],          active: true, gender: "M", level: 2 },
  { id: "emp_53",  employee_code: "E053", full_name: "Kenji Yamamoto",   departments: ["Loading Dock"],                       active: true, gender: "M", level: 3 },
  { id: "emp_54",  employee_code: "E054", full_name: "Fatou Diop",       departments: ["Loading Dock"],                       active: true, gender: "F", level: 1 },
  { id: "emp_55",  employee_code: "E055", full_name: "Bogdan Ionescu",   departments: ["Loading Dock", "Meat Cutting"],       active: true, gender: "M", level: 2 },
  { id: "emp_56",  employee_code: "E056", full_name: "Soo-Jin Lee",      departments: ["Loading Dock"],                       active: true, gender: "F", level: 2 },
  { id: "emp_57",  employee_code: "E057", full_name: "Bruno Ferreira",   departments: ["Loading Dock"],                       active: true, gender: "M", level: 1 },
  { id: "emp_58",  employee_code: "E058", full_name: "Ingrid Hansen",    departments: ["Loading Dock"],                       active: true, gender: "F", level: 2 },
  { id: "emp_59",  employee_code: "E059", full_name: "Kwame Mensah",     departments: ["Loading Dock"],                       active: true, gender: "M", level: 1 },
  { id: "emp_60",  employee_code: "E060", full_name: "Valentina Russo",  departments: ["Loading Dock", "Packaging"],          active: true, gender: "F", level: 3 },
  { id: "emp_61",  employee_code: "E061", full_name: "Omar Hassan",      departments: ["Loading Dock"],                       active: true, gender: "M", level: 2 },
  // Small Pro
  { id: "emp_62",  employee_code: "E062", full_name: "Lena Fischer",     departments: ["Small Pro"],                          active: true, gender: "F", level: 2 },
  { id: "emp_63",  employee_code: "E063", full_name: "Mei-Ling Zhang",   departments: ["Small Pro", "Processing Floor"],      active: true, gender: "F", level: 1 },
  { id: "emp_64",  employee_code: "E064", full_name: "Tariq Al-Rashid",  departments: ["Small Pro"],                          active: true, gender: "M", level: 3 },
  { id: "emp_65",  employee_code: "E065", full_name: "Aoife Brennan",    departments: ["Small Pro", "Loading Dock"],          active: true, gender: "F", level: 2 },
  { id: "emp_66",  employee_code: "E066", full_name: "Darius Popescu",   departments: ["Small Pro"],                          active: true, gender: "M", level: 1 },
  { id: "emp_67",  employee_code: "E067", full_name: "Yuna Choi",        departments: ["Small Pro"],                          active: true, gender: "F", level: 2 },
  { id: "emp_68",  employee_code: "E068", full_name: "Filippo Romano",   departments: ["Small Pro"],                          active: true, gender: "M", level: 1 },
  { id: "emp_69",  employee_code: "E069", full_name: "Amina Barry",      departments: ["Small Pro"],                          active: true, gender: "F", level: 2 },
  { id: "emp_70",  employee_code: "E070", full_name: "Sienna Walsh",     departments: ["Small Pro"],                          active: true, gender: "F", level: 1 },
  { id: "emp_71",  employee_code: "E071", full_name: "Hamid Nazari",     departments: ["Small Pro", "Packaging"],             active: true, gender: "M", level: 3 },
  { id: "emp_72",  employee_code: "E072", full_name: "Piotr Kowalczyk",  departments: ["Small Pro"],                          active: true, gender: "M", level: 2 },
  { id: "emp_73",  employee_code: "E073", full_name: "Selene Martin",    departments: ["Small Pro"],                          active: true, gender: "F", level: 1 },
  // Processing Floor
  { id: "emp_74",  employee_code: "E074", full_name: "Takeshi Mori",     departments: ["Processing Floor", "Meat Cutting"],   active: true, gender: "M", level: 3 },
  { id: "emp_75",  employee_code: "E075", full_name: "Abebe Bekele",     departments: ["Processing Floor"],                   active: true, gender: "M", level: 2 },
  { id: "emp_76",  employee_code: "E076", full_name: "Caitlin Murphy",   departments: ["Processing Floor"],                   active: true, gender: "F", level: 1 },
  { id: "emp_77",  employee_code: "E077", full_name: "Rafael Herrera",   departments: ["Processing Floor", "Loading Dock"],   active: true, gender: "M", level: 2 },
  { id: "emp_78",  employee_code: "E078", full_name: "Helga Lindqvist",  departments: ["Processing Floor"],                   active: true, gender: "F", level: 3 },
  { id: "emp_79",  employee_code: "E079", full_name: "Moussa Coulibaly", departments: ["Processing Floor"],                   active: true, gender: "M", level: 1 },
  { id: "emp_80",  employee_code: "E080", full_name: "Jing Wei",         departments: ["Processing Floor"],                   active: true, gender: "F", level: 2 },
  { id: "emp_81",  employee_code: "E081", full_name: "Tobias Krause",    departments: ["Processing Floor"],                   active: true, gender: "M", level: 2 },
  { id: "emp_82",  employee_code: "E082", full_name: "Zanele Mokoena",   departments: ["Processing Floor", "Small Pro"],      active: true, gender: "F", level: 1 },
  { id: "emp_83",  employee_code: "E083", full_name: "Guillermo Perez",  departments: ["Processing Floor"],                   active: true, gender: "M", level: 3 },
  { id: "emp_84",  employee_code: "E084", full_name: "Nora Strand",      departments: ["Processing Floor"],                   active: true, gender: "F", level: 2 },
  // Meat Cutting
  { id: "emp_85",  employee_code: "E085", full_name: "Raj Sharma",       departments: ["Meat Cutting", "Packaging"],          active: true, gender: "M", level: 3 },
  { id: "emp_86",  employee_code: "E086", full_name: "Ekaterina Ivanova",departments: ["Meat Cutting"],                       active: true, gender: "F", level: 2 },
  { id: "emp_87",  employee_code: "E087", full_name: "Ismail Traore",    departments: ["Meat Cutting"],                       active: true, gender: "M", level: 1 },
  { id: "emp_88",  employee_code: "E088", full_name: "Carmen Flores",    departments: ["Meat Cutting", "Processing Floor"],   active: true, gender: "F", level: 2 },
  { id: "emp_89",  employee_code: "E089", full_name: "Mikael Eriksson",  departments: ["Meat Cutting"],                       active: true, gender: "M", level: 3 },
  { id: "emp_90",  employee_code: "E090", full_name: "Adaeze Eze",       departments: ["Meat Cutting"],                       active: true, gender: "F", level: 1 },
  { id: "emp_91",  employee_code: "E091", full_name: "Stefan Weber",     departments: ["Meat Cutting"],                       active: true, gender: "M", level: 2 },
  // Packaging
  { id: "emp_92",  employee_code: "E092", full_name: "Layla Mahmoud",    departments: ["Packaging", "Loading Dock"],          active: true, gender: "F", level: 2 },
  { id: "emp_93",  employee_code: "E093", full_name: "Chidi Okeke",      departments: ["Packaging"],                          active: true, gender: "M", level: 1 },
  { id: "emp_94",  employee_code: "E094", full_name: "Astrid Larsen",    departments: ["Packaging"],                          active: true, gender: "F", level: 3 },
  { id: "emp_95",  employee_code: "E095", full_name: "Felipe Castillo",  departments: ["Packaging"],                          active: true, gender: "M", level: 2 },
  { id: "emp_96",  employee_code: "E096", full_name: "Naomi Watanabe",   departments: ["Packaging"],                          active: true, gender: "F", level: 1 },
  { id: "emp_97",  employee_code: "E097", full_name: "Jerome Dupont",    departments: ["Packaging", "Small Pro"],             active: true, gender: "M", level: 2 },
  { id: "emp_98",  employee_code: "E098", full_name: "Sunita Rao",       departments: ["Packaging"],                          active: true, gender: "F", level: 1 },
  { id: "emp_99",  employee_code: "E099", full_name: "Brendan Gallagher",departments: ["Packaging"],                          active: true, gender: "M", level: 3 },
  { id: "emp_100", employee_code: "E100", full_name: "Zainab Al-Farsi",  departments: ["Packaging"],                          active: true, gender: "F", level: 2 },
  // Unassigned / Temporary
  { id: "emp_101", employee_code: "E101", full_name: "Tyler Brooks",     departments: [], active: true, gender: "M", level: 1, temporary: true },
  { id: "emp_102", employee_code: "E102", full_name: "Hana Kato",        departments: [], active: true, gender: "F", level: 1 },
  { id: "emp_103", employee_code: "E103", full_name: "Emmanuel Osei",    departments: [], active: true, gender: "M", level: 2 },
  { id: "emp_104", employee_code: "E104", full_name: "Sofia Reyes",      departments: [], active: true, gender: "F", level: 1, temporary: true },
  { id: "emp_105", employee_code: "E105", full_name: "Noah Bergmann",    departments: [], active: true, gender: "M", level: 1 },
  { id: "emp_106", employee_code: "E106", full_name: "Amara Sy",         departments: [], active: true, gender: "F", level: 2 },
  { id: "emp_107", employee_code: "E107", full_name: "Lucas Oliveira",   departments: [], active: true, gender: "M", level: 1, temporary: true },
  { id: "emp_108", employee_code: "E108", full_name: "Yuki Nakamura",    departments: [], active: true, gender: "F", level: 1 },
  { id: "emp_109", employee_code: "E109", full_name: "Isla MacKenzie",   departments: [], active: true, gender: "F", level: 2 },
  { id: "emp_110", employee_code: "E110", full_name: "Kofi Asante",      departments: [], active: true, gender: "M", level: 1 },
];

export const mockEmployeeStatuses: EmployeeDailyStatus[] = [
  { id: "status_1", employee_id: "emp_1", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "available", reason: null },
  { id: "status_2", employee_id: "emp_2", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "available", reason: null },
  { id: "status_3", employee_id: "emp_3", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "available", reason: null },
  { id: "status_4", employee_id: "emp_4", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "vacation", reason: "Family event" },
  { id: "status_5", employee_id: "emp_5", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "available", reason: null },
  { id: "status_6", employee_id: "emp_6", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "available", reason: null },
  { id: "status_7", employee_id: "emp_7", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "sick", reason: "Not feeling well" },
  { id: "status_101", employee_id: "emp_101", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_102", employee_id: "emp_102", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_103", employee_id: "emp_103", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_104", employee_id: "emp_104", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_105", employee_id: "emp_105", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_106", employee_id: "emp_106", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_107", employee_id: "emp_107", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_108", employee_id: "emp_108", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_109", employee_id: "emp_109", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
  { id: "status_110", employee_id: "emp_110", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal", status: "unassigned", reason: null },
];

export const mockAssignments: StationAssignment[] = [
  // Loading Dock - shift 1
  { id: "a1", employee_id: "emp_5", station_id: "st_loading_supervisor", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a2", employee_id: "emp_8", station_id: "st_loading_helper_1", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  // Loading Dock - shift 2
  { id: "a3", employee_id: "emp_5", station_id: "st_loading_supervisor", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  // Packaging - hog_break - shift 1
  { id: "a4", employee_id: "emp_1", station_id: "st_supervisor", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a5", employee_id: "emp_2", station_id: "st_lead", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a6", employee_id: "emp_9", station_id: "st_lead", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  // Packaging - after_hog_break - shift 1
  { id: "a7", employee_id: "emp_1", station_id: "st_ahb_supervisor", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a8", employee_id: "emp_10", station_id: "st_ahb_lead", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  // Small Pro
  { id: "a9", employee_id: "emp_6", station_id: "st_small_slab_off", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  // Meat Cutting - hog_break
  { id: "a10", employee_id: "emp_7", station_id: "st_meat_saw", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a11", employee_id: "emp_4", station_id: "st_meat_saw", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a12", employee_id: "emp_3", station_id: "st_meat_neck_bones", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  // Meat Cutting - after_hog_break
  { id: "a13", employee_id: "emp_7", station_id: "st_ahb_meat_saw", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a14", employee_id: "emp_4", station_id: "st_ahb_meat_proof", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a15", employee_id: "emp_3", station_id: "st_ahb_meat_saw", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  // Processing Floor
  { id: "a16", employee_id: "emp_11", station_id: "st_proc_barn_setup", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a17", employee_id: "emp_17", station_id: "st_proc_blood_pit", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  // Meat Cutting - emp_12, emp_16
  { id: "a18", employee_id: "emp_12", station_id: "st_meat_rib_1", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a19", employee_id: "emp_12", station_id: "st_ahb_meat_rib", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a20", employee_id: "emp_16", station_id: "st_meat_rib_2", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a21", employee_id: "emp_16", station_id: "st_ahb_meat_loin_trim", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  // Packaging - emp_13, emp_18
  { id: "a22", employee_id: "emp_13", station_id: "st_end", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a23", employee_id: "emp_13", station_id: "st_ahb_end", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a24", employee_id: "emp_18", station_id: "st_feed", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a25", employee_id: "emp_18", station_id: "st_ahb_feed", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  // Loading Dock - emp_14, emp_20
  { id: "a26", employee_id: "emp_14", station_id: "st_loading_helper_2", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a27", employee_id: "emp_20", station_id: "st_loading_hogselector", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  // Small Pro - emp_15, emp_19
  { id: "a28", employee_id: "emp_15", station_id: "st_small_slab_on", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a29", employee_id: "emp_19", station_id: "st_small_slab_garlic", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  // Loading Dock - emp_21-25
  { id: "a30", employee_id: "emp_21", station_id: "st_loading_cooler", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a31", employee_id: "emp_22", station_id: "st_loading_maps_helper", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a32", employee_id: "emp_23", station_id: "st_loading_helper_3", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a33", employee_id: "emp_24", station_id: "st_loading_helper_4", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a34", employee_id: "emp_25", station_id: "st_loading_helper_5", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  // Small Pro - emp_26-30
  { id: "a35", employee_id: "emp_26", station_id: "st_small_euro", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a36", employee_id: "emp_27", station_id: "st_small_sandwich", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a37", employee_id: "emp_28", station_id: "st_small_jowl", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a38", employee_id: "emp_29", station_id: "st_small_back_rib", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a39", employee_id: "emp_30", station_id: "st_small_spare_rib", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  // Processing Floor - emp_31-37
  { id: "a40", employee_id: "emp_31", station_id: "st_proc_clean_side", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a41", employee_id: "emp_32", station_id: "st_proc_blood_setup", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a42", employee_id: "emp_33", station_id: "st_proc_suckling_tank", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a43", employee_id: "emp_34", station_id: "st_proc_rollers_gams", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a44", employee_id: "emp_35", station_id: "st_proc_bone_heads", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a45", employee_id: "emp_36", station_id: "st_proc_barn_setup", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a46", employee_id: "emp_37", station_id: "st_proc_blood_pit", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  // Meat Cutting - emp_38-45 (hog_break + after_hog_break)
  { id: "a47", employee_id: "emp_38", station_id: "st_meat_proof", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a48", employee_id: "emp_38", station_id: "st_ahb_meat_proof", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a49", employee_id: "emp_39", station_id: "st_meat_skinner", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a50", employee_id: "emp_39", station_id: "st_ahb_meat_skinner", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a51", employee_id: "emp_40", station_id: "st_meat_whiz_knife", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a52", employee_id: "emp_40", station_id: "st_ahb_meat_picnic", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a53", employee_id: "emp_41", station_id: "st_meat_picnic_1", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a54", employee_id: "emp_41", station_id: "st_ahb_meat_picnic", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a55", employee_id: "emp_42", station_id: "st_meat_picnic_2", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a56", employee_id: "emp_42", station_id: "st_ahb_meat_rib", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a57", employee_id: "emp_43", station_id: "st_meat_loin_trim", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a58", employee_id: "emp_43", station_id: "st_ahb_meat_loin_trim", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a59", employee_id: "emp_44", station_id: "st_meat_loin_butt", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a60", employee_id: "emp_44", station_id: "st_ahb_meat_loin_butt", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a61", employee_id: "emp_45", station_id: "st_meat_butt_trim", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a62", employee_id: "emp_45", station_id: "st_ahb_meat_butt_trim", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  // Packaging - emp_46-50 (hog_break + after_hog_break)
  { id: "a63", employee_id: "emp_46", station_id: "st_end", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a64", employee_id: "emp_46", station_id: "st_ahb_end", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a65", employee_id: "emp_47", station_id: "st_lead", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a66", employee_id: "emp_47", station_id: "st_ahb_lead", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a67", employee_id: "emp_48", station_id: "st_feed", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a68", employee_id: "emp_48", station_id: "st_ahb_feed", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a69", employee_id: "emp_49", station_id: "st_supervisor", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a70", employee_id: "emp_49", station_id: "st_ahb_supervisor", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a71", employee_id: "emp_50", station_id: "st_end", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a72", employee_id: "emp_50", station_id: "st_ahb_end", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  // Loading Dock - emp_51-61
  { id: "a73", employee_id: "emp_51", station_id: "st_loading_helper_2", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a74", employee_id: "emp_52", station_id: "st_loading_helper_3", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a75", employee_id: "emp_53", station_id: "st_loading_hogselector", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a76", employee_id: "emp_54", station_id: "st_loading_cooler", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a77", employee_id: "emp_55", station_id: "st_loading_maps_helper", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a78", employee_id: "emp_56", station_id: "st_loading_helper_4", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a79", employee_id: "emp_57", station_id: "st_loading_helper_5", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a80", employee_id: "emp_58", station_id: "st_loading_helper_6", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a81", employee_id: "emp_59", station_id: "st_loading_supervisor", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a82", employee_id: "emp_60", station_id: "st_loading_helper_1", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a83", employee_id: "emp_61", station_id: "st_loading_helper_3", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  // Small Pro - emp_62-73
  { id: "a84", employee_id: "emp_62", station_id: "st_small_slab_jalapeno", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a85", employee_id: "emp_63", station_id: "st_small_slab_maple", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a86", employee_id: "emp_64", station_id: "st_small_slab_nna", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a87", employee_id: "emp_65", station_id: "st_small_slab_sugar_free", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a88", employee_id: "emp_66", station_id: "st_small_slab_off", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a89", employee_id: "emp_67", station_id: "st_small_slab_on", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a90", employee_id: "emp_68", station_id: "st_small_slab_garlic", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a91", employee_id: "emp_69", station_id: "st_small_euro", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a92", employee_id: "emp_70", station_id: "st_small_sandwich", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a93", employee_id: "emp_71", station_id: "st_small_banquet", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a94", employee_id: "emp_72", station_id: "st_small_kaiser", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a95", employee_id: "emp_73", station_id: "st_small_custom", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  // Processing Floor - emp_74-84
  { id: "a96", employee_id: "emp_74", station_id: "st_proc_barn_setup", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a97", employee_id: "emp_75", station_id: "st_proc_blood_pit", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a98", employee_id: "emp_76", station_id: "st_proc_clean_side", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a99", employee_id: "emp_77", station_id: "st_proc_blood_setup", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a100", employee_id: "emp_78", station_id: "st_proc_suckling_tank", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a101", employee_id: "emp_79", station_id: "st_proc_rollers_gams", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a102", employee_id: "emp_80", station_id: "st_proc_bone_heads", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a103", employee_id: "emp_81", station_id: "st_proc_barn_setup", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "normal" },
  { id: "a104", employee_id: "emp_82", station_id: "st_proc_blood_pit", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  { id: "a105", employee_id: "emp_83", station_id: "st_proc_clean_side", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "normal" },
  { id: "a106", employee_id: "emp_84", station_id: "st_proc_suckling_tank", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "normal" },
  // Meat Cutting - emp_85-91
  { id: "a107", employee_id: "emp_85", station_id: "st_meat_small_saw", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a108", employee_id: "emp_85", station_id: "st_ahb_meat_small_saw", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a109", employee_id: "emp_86", station_id: "st_meat_float", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "hog_break" },
  { id: "a110", employee_id: "emp_86", station_id: "st_ahb_meat_cleanup", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "after_hog_break" },
  { id: "a111", employee_id: "emp_87", station_id: "st_meat_bellies_1", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a112", employee_id: "emp_87", station_id: "st_ahb_meat_bellies_1", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a113", employee_id: "emp_88", station_id: "st_meat_bellies_2", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "hog_break" },
  { id: "a114", employee_id: "emp_88", station_id: "st_ahb_meat_bellies_2", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "after_hog_break" },
  { id: "a115", employee_id: "emp_89", station_id: "st_meat_bellies_3", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a116", employee_id: "emp_89", station_id: "st_ahb_meat_bellies_3", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a117", employee_id: "emp_90", station_id: "st_meat_bellies_4", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "hog_break" },
  { id: "a118", employee_id: "emp_90", station_id: "st_ahb_meat_bellies_1", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "after_hog_break" },
  { id: "a119", employee_id: "emp_91", station_id: "st_meat_cr_proof", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a120", employee_id: "emp_91", station_id: "st_ahb_meat_cr_1", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  // Packaging - emp_92-100
  { id: "a121", employee_id: "emp_92", station_id: "st_pack_box_trim", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a122", employee_id: "emp_92", station_id: "st_ahb_pack_floater", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a123", employee_id: "emp_93", station_id: "st_pack_dump_barrels", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "hog_break" },
  { id: "a124", employee_id: "emp_93", station_id: "st_ahb_pack_cleanup", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "after_hog_break" },
  { id: "a125", employee_id: "emp_94", station_id: "st_pack_bellie", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a126", employee_id: "emp_94", station_id: "st_ahb_pack_bellie", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a127", employee_id: "emp_95", station_id: "st_pack_floater", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "hog_break" },
  { id: "a128", employee_id: "emp_95", station_id: "st_ahb_pack_floater", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "after_hog_break" },
  { id: "a129", employee_id: "emp_96", station_id: "st_pack_overstock", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a130", employee_id: "emp_96", station_id: "st_ahb_pack_vac_pac", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a131", employee_id: "emp_97", station_id: "st_pack_offal", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "hog_break" },
  { id: "a132", employee_id: "emp_97", station_id: "st_ahb_pack_offal", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "after_hog_break" },
  { id: "a133", employee_id: "emp_98", station_id: "st_pack_sungiven", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "hog_break" },
  { id: "a134", employee_id: "emp_98", station_id: "st_ahb_pack_sungiven", work_date: mockWorkDate, shift_code: "shift_2", mode_code: "after_hog_break" },
  { id: "a135", employee_id: "emp_99", station_id: "st_pack_downstairs_lead", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "hog_break" },
  { id: "a136", employee_id: "emp_99", station_id: "st_ahb_pack_downstairs", work_date: mockWorkDate, shift_code: "shift_1", mode_code: "after_hog_break" },
  { id: "a137", employee_id: "emp_100", station_id: "st_pack_vac_pac_box", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "hog_break" },
  { id: "a138", employee_id: "emp_100", station_id: "st_ahb_pack_vac_box", work_date: mockWorkDate, shift_code: "shift_3", mode_code: "after_hog_break" },
];
